# Generated by Django 3.0.1 on 2019-12-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=30)),
                ('Product_code', models.CharField(max_length=30)),
                ('Product_qty', models.IntegerField()),
                ('Product_price', models.FloatField()),
            ],
            options={
                'db_table': 'Product_details',
            },
        ),
    ]
